[package]
name = "wwe-rust-universe"
version = "0.0.1"
description = "WWE Universe App to log and track your Universe Mode"
authors = ["Kiefer"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15.0"
diesel = { version = "2.0.3", features = ["sqlite"] }
diesel_migrations = "2.0.0"
libsqlite3-sys = { version = "0.28.0", features = ["bundled"] }
log = "0.4.21"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
