name: Test App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Install system dependencies
    - name: Install GTK dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

    # Step 3: Set up Node.js to use Yarn
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node.js version you are using

    # Step 4: Install JavaScript dependencies using Yarn
    - name: Install dependencies
      run: yarn install

    # Step 5: Build the Rust project
    - name: Build Rust project
      run: cargo build --verbose
      working-directory: ./src-tauri  # Specify the directory where Cargo.toml is located

    # Step 6: Run Rust tests from a specific file (test_file.rs)
    - name: Run specific Rust test file
      run: cargo test --verbose  # Optionally: cargo test --test test_file if you want to specify the test file
      working-directory: ./src-tauri  # Specify the directory where Cargo.toml is located
